apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: airflow-redis
  name: airflow-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      run: airflow-redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: airflow-redis
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: IfNotPresent
        name: airflow-redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 5Mi
          requests:
            cpu: 10m
            memory: 2Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
