kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-home
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs
